# Generated by Django 4.2 on 2023-09-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('enlace', models.URLField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('palabra_clave', models.CharField(max_length=50)),
            ],
        ),
    ]
